- hosts: all
  tasks:

  - name: install ambari repo
    get_url:
        url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.2.2/ambari.repo
        dest: /etc/yum.repos.d/ambari.repo

  - yum:
        name: "{{ packages }}"
    vars:
        packages:
        - epel-release

  - yum:
        name: "{{ packages }}"
    vars:
        packages:
        - initscripts
        - net-tools
        - wget
        - curl
        - which
        - openssh-clients
        - openssh
        - sudo
        - screen

  - name: create user admin
    user:
      name: admin
      password: $6$hdp$hN2cUtEK9G.dFvm08GYG7g7pizaK0ZJdwH5k3aCkmI5FRzrLAl84gKI0xrfLpyD0Uwv6L7HRd2kNfLZQxJ7V40



- hosts: ambari
  tasks:

  - yum:
        name: "{{ packages }}"
    vars:
        packages:
        - ambari-server
        - postgresql-server
        - postgresql-jdbc
        - mysql-connector-java

  - name: Copy ambari initialization script
    copy:
      src: init-ambari.sh
      dest: /root/init-ambari.sh
  
  - name: Initialize ambari
    command: bash /root/init-ambari.sh
    args:
      creates: /var/ambari-init-executed


  - name: Setup postgresql
    systemd:
      name: postgresql.service
      state: started
      enabled: yes

  - name: Setup ambari-server
    systemd:
      name: ambari-server.service
      state: started
      enabled: yes

  - name: Wait for ambari to start up
    wait_for:
      host: 172.20.10.1
      port: 8080
      delay: 10
      state: drained
      timeout: 600

  - name: install mysql jdbc driver
    command: ambari-server setup --jdbc-db=mysql --jdbc-driver /usr/share/java/mysql-connector-java.jar
    args:
      creates: /var/lib/ambari-server/resources/mysql-connector-java.jar

  - name: install postgresql jdbc driver
    command: ambari-server setup --jdbc-db=postgres --jdbc-driver /usr/share/java/postgresql-jdbc.jar
    args:
      creates: /var/lib/ambari-server/resources/postgresql-jdbc.jar



  
- hosts: agent
  tasks: 

  - yum:
        name: "{{ packages }}"
    vars:
        packages:
        - ambari-agent

  - name: Copy ambari-agent config
    copy:
      src: ambari-agent.ini
      dest: /etc/ambari-agent/conf/ambari-agent.ini

  - name: Disable python cert verification
    copy:
      src: cert-verification.cfg
      dest: /etc/python/cert-verification.cfg

  - name: Setup ambari-agent
    systemd:
      name: ambari-agent.service
      state: started
      enabled: yes


- hosts: edge
  tasks:

  - yum: 
      name: "{{ packages }}"
    vars:
      packages:
      - python-sqlalchemy
      - python-saslwrapper
      - python-pip
      - gcc-c++
      - cyrus-sasl-devel
      - cyrus-sasl-gssapi
      - cyrus-sasl-sql
      - cyrus-sasl-gs2
      - cyrus-sasl-ldap
      - cyrus-sasl-md5
      - cyrus-sasl-plain
      - python-devel

  - name: install pyhive
    command: pip install pyhive[hive]
    args:
      creates: /usr/lib/python2.7/site-packages/pyhive/common.py